import type {
  ActivityCategoryDefinition,
  ActivityDefinition,
} from "./types";

function createActivities(
  categoryId: string,
  labels: string[],
): ActivityDefinition[] {
  return labels.map((label, index) => ({
    id: `${categoryId}-${label
      .toLowerCase()
      .replace(/&/g, "and")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")}`,
    label,
    order: index + 1,
    active: true,
    isOther: label === "Other",
  }));
}

export const ACTIVITY_CATEGORIES: ActivityCategoryDefinition[] =
  [
    {
      id: "rope",
      icon: "🪢",
      title: "Rope",
      description:
        "Bondage, decorative ties, floor work, restraint, and suspension.",
      order: 1,
      active: true,
      activities: createActivities("rope", [
        "Decorative Rope",
        "Floor Rope",
        "Partial Suspension",
        "Full Suspension",
        "Predicament",
        "Other",
      ]),
    },
    {
      id: "impact",
      icon: "🥁",
      title: "Impact",
      description:
        "Hands, paddles, floggers, canes, whips, and other forms of impact.",
      order: 2,
      active: true,
      activities: createActivities("impact", [
        "Spanking",
        "Punching",
        "Paddles",
        "Canes",
        "Floggers",
        "Whips",
        "Crops",
        "Other",
      ]),
    },
    {
      id: "power-exchange",
      icon: "✨",
      title: "Power Exchange",
      description:
        "Authority, submission, service, control, protocol, and negotiated dynamics.",
      order: 3,
      active: true,
      activities: createActivities(
        "power-exchange",
        [
          "Dominance",
          "Submission",
          "Service",
          "Protocol",
          "Obedience",
          "Bratting",
          "Pet Play",
          "Owner / Property Dynamics",
          "Caregiver / Little Dynamics",
          "Primal",
          "Hunter / Prey",
          "Objectification",
          "Degradation",
          "Praise",
          "Humiliation",
          "Discipline",
          "Punishment",
          "Reward",
          "Other",
        ],
      ),
    },
    {
      id: "sensation",
      icon: "👐",
      title: "Sensation",
      description:
        "Touch, temperature, scratching, sharp sensations, and sensory play.",
      order: 4,
      active: true,
      activities: createActivities("sensation", [
        "Biting",
        "Electricity",
        "Hair Pulling",
        "Knives",
        "Licking",
        "Mind Fuck",
        "Nipple Play",
        "Playing with Hair",
        "Pressure Points",
        "Scratching",
        "Sensory Deprivation",
        "Sharp Play",
        "Tickling",
        "Edge Play",
        "Other",
      ]),
    },
    {
      id: "restraint",
      icon: "🔒",
      title: "Restraint",
      description:
        "Cuffs, chains, furniture, immobilization, and non-rope restraint.",
      order: 5,
      active: true,
      activities: createActivities("restraint", [
        "Handcuffs",
        "Leather Cuffs",
        "Velcro Cuffs",
        "Spreader Bars",
        "Chains",
        "Collars",
        "Gags",
        "Blindfolds",
        "Hoods",
        "Tape",
        "Straitjackets",
        "Bondage Furniture",
        "Stocks / Pillory",
        "Cages / Kennels",
        "Mummification",
        "Other",
      ]),
    },
    {
      id: "roleplay",
      icon: "🎭",
      title: "Roleplay",
      description:
        "Characters, scenarios, fantasy, authority roles, and negotiated scene frameworks.",
      order: 6,
      active: true,
      activities: createActivities("roleplay", [
        "Authority Figure",
        "Medical",
        "Teacher / Student",
        "Boss / Employee",
        "Interrogation",
        "Captive / Captor",
        "Fantasy",
        "Historical",
        "Age Regression",
        "Age Progression",
        "Cosplay",
        "Animal / Creature",
        "Doll / Puppet",
        "Supernatural",
        "Survival",
        "Consensual Non-Consent",
        "Other",
      ]),
    },
    {
      id: "service",
      icon: "🧹",
      title: "Service",
      description:
        "Tasks, care, personal assistance, rituals, and acts of service.",
      order: 7,
      active: true,
      activities: createActivities("service", [
        "Cleaning",
        "Food Service",
        "Beverage Service",
        "Dressing / Undressing",
        "Bootblacking",
        "Personal Assistance",
        "Household Tasks",
        "Acts of Care",
        "Rituals",
        "Position Holding",
        "Object Service",
        "Other",
      ]),
    },
    {
      id: "exposure",
      icon: "👁️",
      title: "Exposure",
      description:
        "Photography, audiences, public settings, visibility, and sharing.",
      order: 8,
      active: true,
      activities: createActivities("exposure", [
        "Photography",
        "Video Recording",
        "Live Streaming",
        "Public Settings",
        "Private Events",
        "Parties / Dungeons",
        "Audience Participation",
        "Being Observed",
        "Being Heard",
        "Sharing Images",
        "Sharing Stories",
        "Other",
      ]),
    },
    {
      id: "intimacy",
      icon: "💗",
      title: "Intimacy",
      description:
        "Affection, kissing, sexual activities, romantic interaction, and penetration.",
      order: 9,
      active: true,
      activities: createActivities("intimacy", [
        "Affectionate Touching",
        "Cuddling",
        "Kissing",
        "Massage",
        "Sensual Touching",
        "Nudity",
        "Mutual Masturbation",
        "Oral Sex",
        "Vaginal Penetration",
        "Anal Penetration",
        "Manual Stimulation",
        "Toys",
        "Body Fluids",
        "Orgasm Control",
        "Chastity",
        "Voyeurism",
        "Exhibitionism",
        "Other",
      ]),
    },
    {
      id: "medical-play",
      icon: "🩺",
      title: "Medical Play",
      description:
        "Examinations, caretaking, medical tools, restraints, and clinical activities.",
      order: 10,
      active: true,
      activities: createActivities(
        "medical-play",
        [
          "Examinations",
          "Gloves",
          "Medical Instruments",
          "Needles",
          "Suturing / Stapling",
          "Bandaging",
          "Enemas",
          "Catheters",
          "Speculums",
          "Electro-Medical Devices",
          "Medical Restraints",
          "Vital Sign Monitoring",
          "Caretaking",
          "Aftercare Role",
          "Other",
        ],
      ),
    },
 {
  id: "other-notes",
  icon: "⭐",
  title: "Other Activities & Interests",
  description:
    "Anything not covered above that you'd like your partner to know or discuss.",
  order: 11,
  active: true,
  activities: [
    {
      id: "other-notes",
      label: "Additional Notes",
      order: 1,
      active: true,
      isOther: true,
    },
  ],
},
  ];